#---------------------------------------------------------------------
# Manifest File to create AWS EKS Cluster in Custom VPC
#
# eksctl create cluster -f eks-cluster.yaml
# eksctl delete cluster -f eks-cluster.yaml
#
# Copyleft (c) by Denis Astahov 2021
#---------------------------------------------------------------------
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name  : demo-prod-new-new-new-new
  region: us-east-1

vpc:
 id     : "vpc-071c7ad43e361b80f"
 subnets:
   public:
      us-east-1a: { id: subnet-088ede340226bc635 }  # For Load Balancer
      us-east-1b: { id: subnet-08b7232a0753ea530 }  # For Load Balancer
   private:
      us-east-1c: { id: subnet-004468d1ce0f241eb }  # For Worker Nodes
      us-east-1d: { id: subnet-01dab09e1368e6d6a }  # For Worker Nodes

managedNodeGroups:
  - name             : worker
    instanceType     : t2.micro
    labels           : { role: general }
    desiredCapacity  : 1
    volumeSize       : 80
    privateNetworking: true                         # Use Private Subnets
