apiVersion: v1 
kind: Pod 
metadata:
  name  : my-web
spec:
  containers:
  - name: khodzha
    image: azizkhodzhaev/k8sphp:latest
    ports:
      - containerPort: 80
  imagePullSecrets:
  - name: dockerhub-secret